server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # เปลี่ยนชื่อ host ให้ตรงกับชื่อ service ใน docker-compose.yml และแก้ Port ให้ตรงกับ expose
        proxy_pass http://identity-api:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}